/**
 * Authoritative Authentication & RBAC Constants for HambakTech
 */

export const ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMIN: "admin",
  STAFF: "staff",
  MANAGER: "manager",
  DEVELOPER: "developer",
  AGENT: "agent",
  CUSTOMER: "customer",
  STUDENT: "student",
} as const;

export type RoleSlugType = typeof ROLES[keyof typeof ROLES];

export const PERMISSIONS = {
  // Users & RBAC
  USERS_READ: "users.read",
  USERS_UPDATE: "users.update",
  USERS_MANAGE: "users.manage",
  USERS_VIEW: "users.view",
  RBAC_MANAGE: "rbac.manage",

  // Orders
  ORDERS_READ: "orders.read",
  ORDERS_UPDATE: "orders.update",
  ORDERS_PROCESS: "orders.process",
  ORDERS_CREATE: "orders.create",
  ORDERS_MANAGE: "orders.manage",

  // Wallets & Finance
  WALLET_READ: "wallet.read",
  WALLET_ADJUST: "wallet.adjust",
  WALLETS_MANAGE: "wallets.manage",
  FINANCE_AUDIT: "finance.audit",
  REPORTS_READ: "reports.read",

  // Services
  SERVICES_READ: "services.read",
  SERVICES_MANAGE: "services.manage",
  SERVICES_VIEW: "services.view",

  // Settings & Audit
  SETTINGS_READ: "settings.read",
  SETTINGS_MANAGE: "settings.manage",
  SYSTEM_SETTINGS: "system.settings",
  AUDIT_READ: "audit.read",
  PRICING_READ: "pricing.read",
  PRICING_MANAGE: "pricing.manage",
  PROFILE_READ: "profile.read",
  PROFILE_UPDATE: "profile.update",

  // Operations Desks
  NIN_READ: "nin.read",
  NIN_PROCESS: "nin.process",
  CAC_READ: "cac.read",
  CAC_PROCESS: "cac.process",
  ACADEMY_READ: "academy.read",
  ACADEMY_MANAGE: "academy.manage",

  // Support & CMS
  SUPPORT_READ: "support.read",
  SUPPORT_UPDATE: "support.update",
  SUPPORT_MANAGE: "support.manage",
  CMS_MANAGE: "cms.manage",

  // Shop, Products & Inventory
  PRODUCTS_READ: "products.read",
  PRODUCTS_MANAGE: "products.manage",
  INVENTORY_READ: "inventory.read",
  INVENTORY_MANAGE: "inventory.manage",
  DELIVERY_MANAGE: "delivery.manage",
  CATEGORIES_MANAGE: "categories.manage",
} as const;

export type PermissionSlugType = typeof PERMISSIONS[keyof typeof PERMISSIONS];

/**
 * Baseline Role-to-Permissions Mapping Matrix
 * Strictly enforced server-side.
 */
export const ROLE_PERMISSIONS_MATRIX: Record<RoleSlugType, string[]> = {
  [ROLES.SUPER_ADMIN]: ["*"], // Wildcard: unrestricted access

  [ROLES.ADMIN]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.ORDERS_PROCESS,
    PERMISSIONS.ORDERS_MANAGE,
    PERMISSIONS.WALLET_READ,
    PERMISSIONS.WALLET_ADJUST,
    PERMISSIONS.WALLETS_MANAGE,
    PERMISSIONS.FINANCE_AUDIT,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.SERVICES_MANAGE,
    PERMISSIONS.SERVICES_VIEW,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.NIN_READ,
    PERMISSIONS.NIN_PROCESS,
    PERMISSIONS.CAC_READ,
    PERMISSIONS.CAC_PROCESS,
    PERMISSIONS.ACADEMY_READ,
    PERMISSIONS.ACADEMY_MANAGE,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_UPDATE,
    PERMISSIONS.SUPPORT_MANAGE,
    PERMISSIONS.CMS_MANAGE,
    PERMISSIONS.PRICING_READ,
    PERMISSIONS.PRICING_MANAGE,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.DELIVERY_MANAGE,
    PERMISSIONS.CATEGORIES_MANAGE,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.WALLET_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.SERVICES_VIEW,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.NIN_READ,
    PERMISSIONS.CAC_READ,
    PERMISSIONS.ACADEMY_READ,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_UPDATE,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.DELIVERY_MANAGE,
  ],

  [ROLES.STAFF]: [
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.ORDERS_UPDATE,
    PERMISSIONS.ORDERS_PROCESS,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.SERVICES_VIEW,
    PERMISSIONS.NIN_READ,
    PERMISSIONS.NIN_PROCESS,
    PERMISSIONS.CAC_READ,
    PERMISSIONS.CAC_PROCESS,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_UPDATE,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.INVENTORY_READ,
  ],

  [ROLES.DEVELOPER]: [
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.SERVICES_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
  ],

  [ROLES.AGENT]: [
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.WALLET_READ,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
  ],

  [ROLES.CUSTOMER]: [
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.WALLET_READ,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.ACADEMY_READ,
    PERMISSIONS.ORDERS_READ,
    PERMISSIONS.WALLET_READ,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,
  ],
};

export const AUTH_CONFIG = {
  SESSION_COOKIE_NAME: "ht_session",
  SESSION_EXPIRATION_DAYS: 7,
  REMEMBER_ME_EXPIRATION_DAYS: 30,
  PASSWORD_RESET_EXPIRATION_HOURS: 1,
  EMAIL_VERIFICATION_EXPIRATION_HOURS: 24,
  PASSWORD_MIN_LENGTH: 8,
};
